/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) p_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

void CASADI_PREFIX(fill_n)(real_t* x, int n, real_t alpha) {
  int i;
  for (i=0; i<n; ++i) *x++ = alpha;
}
#define fill_n(x, n, alpha) CASADI_PREFIX(fill_n)(x, n, alpha)


void CASADI_PREFIX(copy_n)(const real_t* x, int n, real_t* y) {
  int i;
  for (i=0; i<n; ++i) *y++ = *x++;
}
#define copy_n(x, n, y) CASADI_PREFIX(copy_n)(x, n, y)


static const int CASADI_PREFIX(s0)[] = {1, 1, 0, 1, 0};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {1, 2, 0, 1, 2, 0, 0};
#define s1 CASADI_PREFIX(s1)
/* fwd2_f */
static int CASADI_PREFIX(f0)(const real_t** arg, real_t** res, int* iw, real_t* w) {
  real_t a0=arg[0] ? arg[0][0] : 0;
  real_t a1=(a0+a0);
  real_t a2=arg[3] ? arg[3][0] : 0;
  real_t a3=(a1*a2);
  real_t a4=arg[1] ? arg[1][0] : 0;
  a4=(a0+a4);
  real_t a5=sin(a4);
  a3=(a5*a3);
  real_t a6=arg[4] ? arg[4][0] : 0;
  a2=(a2+a6);
  a4=cos(a4);
  a2=(a4*a2);
  a0=sq(a0);
  a2=(a0*a2);
  a3=(a3+a2);
  a3=(a3-a6);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[5] ? arg[5][0] : 0;
  a1=(a1*a3);
  a5=(a5*a1);
  a1=arg[6] ? arg[6][0] : 0;
  a3=(a3+a1);
  a4=(a4*a3);
  a0=(a0*a4);
  a5=(a5+a0);
  a5=(a5-a1);
  if (res[1]!=0) res[1][0]=a5;
  return 0;
}

#define f0(arg, res, iw, w) CASADI_PREFIX(f0)(arg, res, iw, w)

/* f_jac */
int p(const real_t** arg, real_t** res, int* iw, real_t* w) {
  int i, j, k, *ii, *jj, *kk;
  const int *cii;
  real_t r, s, t, *rr, *ss, *tt;
  const real_t *cr, *cs, *ct;
  const real_t** arg1=arg+2;
  real_t** res1=res+1;
  real_t w0, w1, w2, w3, w5, w6, w7, w8, *w9=w+15;
  w0 = 1.;
  w1 = w0;
  w0 = 1.;
  w2 = w0;
  w0 = arg[0] ? arg[0][0] : 0;
  w3 = arg[1] ? arg[1][0] : 0;
  w5 = 0.;
  w6 = 0.;
  arg1[0]=(&w0);
  arg1[1]=(&w3);
  arg1[2]=0;
  arg1[3]=(&w1);
  arg1[4]=(&w5);
  arg1[5]=(&w6);
  arg1[6]=(&w2);
  res1[0]=(&w7);
  res1[1]=(&w8);
  if (f0(arg1, res1, iw, w)) return 1;
  fill_n(w9, 2, 0.);
  for (rr=w9+0, ss=(&w7); rr!=w9+1; rr+=1) *rr += *ss++;
  w7 = 0.;
  for (rr=w9+1, ss=(&w7); rr!=w9+2; rr+=1) *rr = *ss++;
  for (rr=w9+1, ss=(&w8); rr!=w9+2; rr+=1) *rr += *ss++;
  if (res[0]) copy_n(w9, 2, res[0]);
  return 0;
}

int p_init(int *f_type, int *n_in, int *n_out, int *sz_arg, int* sz_res) {
  *f_type = 1;
  *n_in = 2;
  *n_out = 1;
  *sz_arg = 9;
  *sz_res = 3;
  return 0;
}

int p_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row) {
  const int* s;
  switch (i) {
    case 0:
    case 1:
      s = s0; break;
    case 2:
      s = s1; break;
    default:
      return 1;
  }

  *nrow = s[0];
  *ncol = s[1];
  *colind = s + 2;
  *row = s + 2 + (*ncol + 1);
  return 0;
}

int p_work(int *sz_iw, int *sz_w) {
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 17;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
